%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_aging_research';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'epsgc'};
M_.exo_names_tex(1) = {'epsgc'};
M_.exo_names_long(1) = {'epsgc'};
M_.exo_names(2) = {'epsgi'};
M_.exo_names_tex(2) = {'epsgi'};
M_.exo_names_long(2) = {'epsgi'};
M_.exo_names(3) = {'epsa'};
M_.exo_names_tex(3) = {'epsa'};
M_.exo_names_long(3) = {'epsa'};
M_.exo_names(4) = {'epsv'};
M_.exo_names_tex(4) = {'epsv'};
M_.exo_names_long(4) = {'epsv'};
M_.exo_names(5) = {'epsINI'};
M_.exo_names_tex(5) = {'epsINI'};
M_.exo_names_long(5) = {'epsINI'};
M_.exo_names(6) = {'epsTR'};
M_.exo_names_tex(6) = {'epsTR'};
M_.exo_names_long(6) = {'epsTR'};
M_.exo_names(7) = {'epss'};
M_.exo_names_tex(7) = {'epss'};
M_.exo_names_long(7) = {'epss'};
M_.endo_names = cell(34,1);
M_.endo_names_tex = cell(34,1);
M_.endo_names_long = cell(34,1);
M_.endo_names(1) = {'Cw'};
M_.endo_names_tex(1) = {'Cw'};
M_.endo_names_long(1) = {'Cw'};
M_.endo_names(2) = {'Kw'};
M_.endo_names_tex(2) = {'Kw'};
M_.endo_names_long(2) = {'Kw'};
M_.endo_names(3) = {'bw'};
M_.endo_names_tex(3) = {'bw'};
M_.endo_names_long(3) = {'bw'};
M_.endo_names(4) = {'w'};
M_.endo_names_tex(4) = {'w'};
M_.endo_names_long(4) = {'w'};
M_.endo_names(5) = {'hw'};
M_.endo_names_tex(5) = {'hw'};
M_.endo_names_long(5) = {'hw'};
M_.endo_names(6) = {'rk'};
M_.endo_names_tex(6) = {'rk'};
M_.endo_names_long(6) = {'rk'};
M_.endo_names(7) = {'R'};
M_.endo_names_tex(7) = {'R'};
M_.endo_names_long(7) = {'R'};
M_.endo_names(8) = {'pi'};
M_.endo_names_tex(8) = {'pi'};
M_.endo_names_long(8) = {'pi'};
M_.endo_names(9) = {'Tw'};
M_.endo_names_tex(9) = {'Tw'};
M_.endo_names_long(9) = {'Tw'};
M_.endo_names(10) = {'Cr'};
M_.endo_names_tex(10) = {'Cr'};
M_.endo_names_long(10) = {'Cr'};
M_.endo_names(11) = {'K'};
M_.endo_names_tex(11) = {'K'};
M_.endo_names_long(11) = {'K'};
M_.endo_names(12) = {'h'};
M_.endo_names_tex(12) = {'h'};
M_.endo_names_long(12) = {'h'};
M_.endo_names(13) = {'GK'};
M_.endo_names_tex(13) = {'GK'};
M_.endo_names_long(13) = {'GK'};
M_.endo_names(14) = {'mc'};
M_.endo_names_tex(14) = {'mc'};
M_.endo_names_long(14) = {'mc'};
M_.endo_names(15) = {'x1'};
M_.endo_names_tex(15) = {'x1'};
M_.endo_names_long(15) = {'x1'};
M_.endo_names(16) = {'x2'};
M_.endo_names_tex(16) = {'x2'};
M_.endo_names_long(16) = {'x2'};
M_.endo_names(17) = {'pistar'};
M_.endo_names_tex(17) = {'pistar'};
M_.endo_names_long(17) = {'pistar'};
M_.endo_names(18) = {'C'};
M_.endo_names_tex(18) = {'C'};
M_.endo_names_long(18) = {'C'};
M_.endo_names(19) = {'I'};
M_.endo_names_tex(19) = {'I'};
M_.endo_names_long(19) = {'I'};
M_.endo_names(20) = {'b'};
M_.endo_names_tex(20) = {'b'};
M_.endo_names_long(20) = {'b'};
M_.endo_names(21) = {'T'};
M_.endo_names_tex(21) = {'T'};
M_.endo_names_long(21) = {'T'};
M_.endo_names(22) = {'GI'};
M_.endo_names_tex(22) = {'GI'};
M_.endo_names_long(22) = {'GI'};
M_.endo_names(23) = {'Y'};
M_.endo_names_tex(23) = {'Y'};
M_.endo_names_long(23) = {'Y'};
M_.endo_names(24) = {'GC'};
M_.endo_names_tex(24) = {'GC'};
M_.endo_names_long(24) = {'GC'};
M_.endo_names(25) = {'lamb'};
M_.endo_names_tex(25) = {'lamb'};
M_.endo_names_long(25) = {'lamb'};
M_.endo_names(26) = {'Iw'};
M_.endo_names_tex(26) = {'Iw'};
M_.endo_names_long(26) = {'Iw'};
M_.endo_names(27) = {'A'};
M_.endo_names_tex(27) = {'A'};
M_.endo_names_long(27) = {'A'};
M_.endo_names(28) = {'v'};
M_.endo_names_tex(28) = {'v'};
M_.endo_names_long(28) = {'v'};
M_.endo_names(29) = {'W'};
M_.endo_names_tex(29) = {'W'};
M_.endo_names_long(29) = {'W'};
M_.endo_names(30) = {'INI'};
M_.endo_names_tex(30) = {'INI'};
M_.endo_names_long(30) = {'INI'};
M_.endo_names(31) = {'INK'};
M_.endo_names_tex(31) = {'INK'};
M_.endo_names_long(31) = {'INK'};
M_.endo_names(32) = {'INKY'};
M_.endo_names_tex(32) = {'INKY'};
M_.endo_names_long(32) = {'INKY'};
M_.endo_names(33) = {'TR'};
M_.endo_names_tex(33) = {'TR'};
M_.endo_names_long(33) = {'TR'};
M_.endo_names(34) = {'s'};
M_.endo_names_tex(34) = {'s'};
M_.endo_names_long(34) = {'s'};
M_.endo_partitions = struct();
M_.param_names = cell(30,1);
M_.param_names_tex = cell(30,1);
M_.param_names_long = cell(30,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'sigma'};
M_.param_names_tex(2) = {'sigma'};
M_.param_names_long(2) = {'sigma'};
M_.param_names(3) = {'mu'};
M_.param_names_tex(3) = {'mu'};
M_.param_names_long(3) = {'mu'};
M_.param_names(4) = {'omega'};
M_.param_names_tex(4) = {'omega'};
M_.param_names_long(4) = {'omega'};
M_.param_names(5) = {'zeta'};
M_.param_names_tex(5) = {'zeta'};
M_.param_names_long(5) = {'zeta'};
M_.param_names(6) = {'alpha'};
M_.param_names_tex(6) = {'alpha'};
M_.param_names_long(6) = {'alpha'};
M_.param_names(7) = {'alphag'};
M_.param_names_tex(7) = {'alphag'};
M_.param_names_long(7) = {'alphag'};
M_.param_names(8) = {'As'};
M_.param_names_tex(8) = {'As'};
M_.param_names_long(8) = {'As'};
M_.param_names(9) = {'delta'};
M_.param_names_tex(9) = {'delta'};
M_.param_names_long(9) = {'delta'};
M_.param_names(10) = {'epsilon'};
M_.param_names_tex(10) = {'epsilon'};
M_.param_names_long(10) = {'epsilon'};
M_.param_names(11) = {'xi'};
M_.param_names_tex(11) = {'xi'};
M_.param_names_long(11) = {'xi'};
M_.param_names(12) = {'phi'};
M_.param_names_tex(12) = {'phi'};
M_.param_names_long(12) = {'phi'};
M_.param_names(13) = {'phipi'};
M_.param_names_tex(13) = {'phipi'};
M_.param_names_long(13) = {'phipi'};
M_.param_names(14) = {'phiy'};
M_.param_names_tex(14) = {'phiy'};
M_.param_names_long(14) = {'phiy'};
M_.param_names(15) = {'psi'};
M_.param_names_tex(15) = {'psi'};
M_.param_names_long(15) = {'psi'};
M_.param_names(16) = {'s_s'};
M_.param_names_tex(16) = {'s\_s'};
M_.param_names_long(16) = {'s_s'};
M_.param_names(17) = {'rhogc'};
M_.param_names_tex(17) = {'rhogc'};
M_.param_names_long(17) = {'rhogc'};
M_.param_names(18) = {'rhogi'};
M_.param_names_tex(18) = {'rhogi'};
M_.param_names_long(18) = {'rhogi'};
M_.param_names(19) = {'rhov'};
M_.param_names_tex(19) = {'rhov'};
M_.param_names_long(19) = {'rhov'};
M_.param_names(20) = {'GC_Y'};
M_.param_names_tex(20) = {'GC\_Y'};
M_.param_names_long(20) = {'GC_Y'};
M_.param_names(21) = {'GI_Y'};
M_.param_names_tex(21) = {'GI\_Y'};
M_.param_names_long(21) = {'GI_Y'};
M_.param_names(22) = {'INI_Y'};
M_.param_names_tex(22) = {'INI\_Y'};
M_.param_names_long(22) = {'INI_Y'};
M_.param_names(23) = {'b_Y'};
M_.param_names_tex(23) = {'b\_Y'};
M_.param_names_long(23) = {'b_Y'};
M_.param_names(24) = {'TR_Y'};
M_.param_names_tex(24) = {'TR\_Y'};
M_.param_names_long(24) = {'TR_Y'};
M_.param_names(25) = {'rhoa'};
M_.param_names_tex(25) = {'rhoa'};
M_.param_names_long(25) = {'rhoa'};
M_.param_names(26) = {'kappa'};
M_.param_names_tex(26) = {'kappa'};
M_.param_names_long(26) = {'kappa'};
M_.param_names(27) = {'rhoa_INI'};
M_.param_names_tex(27) = {'rhoa\_INI'};
M_.param_names_long(27) = {'rhoa_INI'};
M_.param_names(28) = {'rhoINI'};
M_.param_names_tex(28) = {'rhoINI'};
M_.param_names_long(28) = {'rhoINI'};
M_.param_names(29) = {'rhoTR'};
M_.param_names_tex(29) = {'rhoTR'};
M_.param_names_long(29) = {'rhoTR'};
M_.param_names(30) = {'rhos'};
M_.param_names_tex(30) = {'rhos'};
M_.param_names_long(30) = {'rhos'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 34;
M_.param_nbr = 30;
M_.orig_endo_nbr = 34;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 34;
M_.eq_nbr = 34;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 13 0;
 0 14 0;
 0 15 0;
 0 16 0;
 0 17 0;
 0 18 47;
 1 19 0;
 0 20 48;
 0 21 0;
 0 22 0;
 2 23 0;
 0 24 0;
 3 25 0;
 0 26 0;
 0 27 49;
 0 28 50;
 0 29 0;
 0 30 0;
 0 31 0;
 4 32 0;
 0 33 0;
 5 34 0;
 0 35 0;
 6 36 0;
 0 37 51;
 0 38 0;
 7 39 0;
 8 40 0;
 0 41 0;
 9 42 0;
 10 43 0;
 0 44 0;
 11 45 0;
 12 46 0;]';
M_.nstatic = 17;
M_.nfwrd   = 5;
M_.npred   = 12;
M_.nboth   = 0;
M_.nsfwrd   = 5;
M_.nspred   = 12;
M_.ndynamic   = 17;
M_.dynamic_tmp_nbr = [13; 3; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , '1' ;
  2 , 'name' , '2' ;
  3 , 'name' , '3' ;
  4 , 'name' , '4' ;
  5 , 'name' , 'Cr' ;
  6 , 'name' , '6' ;
  7 , 'name' , 'mc' ;
  8 , 'name' , 'x1' ;
  9 , 'name' , 'x2' ;
  10 , 'name' , 'pistar' ;
  11 , 'name' , '11' ;
  12 , 'name' , 'C' ;
  13 , 'name' , 'h' ;
  14 , 'name' , 'K' ;
  15 , 'name' , 'I' ;
  16 , 'name' , 'b' ;
  17 , 'name' , 'T' ;
  18 , 'name' , 'GK' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , '21' ;
  22 , 'name' , '22' ;
  23 , 'name' , 'v' ;
  24 , 'name' , '24' ;
  25 , 'name' , 'Y' ;
  26 , 'name' , 'W' ;
  27 , 'name' , '27' ;
  28 , 'name' , '28' ;
  29 , 'name' , 'INI' ;
  30 , 'name' , '30' ;
  31 , 'name' , '31' ;
  32 , 'name' , '32' ;
  33 , 'name' , 'INKY' ;
  34 , 'name' , '34' ;
};
M_.mapping.Cw.eqidx = [1 12 ];
M_.mapping.Kw.eqidx = [14 ];
M_.mapping.bw.eqidx = [16 ];
M_.mapping.w.eqidx = [2 5 6 7 28 34 ];
M_.mapping.hw.eqidx = [2 13 ];
M_.mapping.rk.eqidx = [3 5 6 7 ];
M_.mapping.R.eqidx = [4 22 28 ];
M_.mapping.pi.eqidx = [4 8 9 10 11 22 28 ];
M_.mapping.Tw.eqidx = [17 ];
M_.mapping.Cr.eqidx = [5 12 ];
M_.mapping.K.eqidx = [6 14 24 25 26 ];
M_.mapping.h.eqidx = [6 13 25 ];
M_.mapping.GK.eqidx = [7 18 25 ];
M_.mapping.mc.eqidx = [7 8 ];
M_.mapping.x1.eqidx = [8 10 ];
M_.mapping.x2.eqidx = [9 10 ];
M_.mapping.pistar.eqidx = [10 11 ];
M_.mapping.C.eqidx = [12 27 ];
M_.mapping.I.eqidx = [15 24 27 ];
M_.mapping.b.eqidx = [16 21 28 ];
M_.mapping.T.eqidx = [17 21 28 ];
M_.mapping.GI.eqidx = [18 20 27 28 ];
M_.mapping.Y.eqidx = [8 9 22 25 27 30 33 ];
M_.mapping.GC.eqidx = [1 19 27 28 ];
M_.mapping.lamb.eqidx = [1 2 3 4 8 9 ];
M_.mapping.Iw.eqidx = [15 ];
M_.mapping.A.eqidx = [25 30 ];
M_.mapping.v.eqidx = [22 23 ];
M_.mapping.W.eqidx = [5 14 15 26 ];
M_.mapping.INI.eqidx = [27 28 29 30 31 ];
M_.mapping.INK.eqidx = [29 33 ];
M_.mapping.INKY.eqidx = [33 ];
M_.mapping.TR.eqidx = [5 28 32 ];
M_.mapping.s.eqidx = [5 28 34 ];
M_.mapping.epsgc.eqidx = [19 ];
M_.mapping.epsgi.eqidx = [20 ];
M_.mapping.epsa.eqidx = [30 ];
M_.mapping.epsv.eqidx = [23 ];
M_.mapping.epsINI.eqidx = [31 ];
M_.mapping.epsTR.eqidx = [32 ];
M_.mapping.epss.eqidx = [34 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [7 11 13 20 22 24 27 28 30 31 33 34 ];
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(34, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(30, 1);
M_.endo_trends = struct('deflator', cell(34, 1), 'log_deflator', cell(34, 1), 'growth_factor', cell(34, 1), 'log_growth_factor', cell(34, 1));
M_.NNZDerivatives = [122; -1; -1; ];
M_.static_tmp_nbr = [13; 3; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 0.99;
beta = M_.params(1);
M_.params(2) = 1;
sigma = M_.params(2);
M_.params(3) = 2;
mu = M_.params(3);
M_.params(4) = 0.6;
omega = M_.params(4);
M_.params(5) = 0.4;
zeta = M_.params(5);
M_.params(6) = 0.3333333333333333;
alpha = M_.params(6);
M_.params(7) = 0.129;
alphag = M_.params(7);
M_.params(8) = 1;
As = M_.params(8);
M_.params(9) = 0.028;
delta = M_.params(9);
M_.params(10) = 11;
epsilon = M_.params(10);
M_.params(11) = 0.8;
xi = M_.params(11);
set_param_value('phi',phi);
M_.params(13) = 1.5;
phipi = M_.params(13);
M_.params(14) = 0.1;
phiy = M_.params(14);
M_.params(15) = 0.1;
psi = M_.params(15);
M_.params(16) = 0.4006;
s_s = M_.params(16);
M_.params(17) = 0.9;
rhogc = M_.params(17);
M_.params(18) = 0.9;
rhogi = M_.params(18);
M_.params(29) = 0.9;
rhoTR = M_.params(29);
M_.params(19) = 0.5;
rhov = M_.params(19);
M_.params(20) = 0.16;
GC_Y = M_.params(20);
M_.params(21) = 0.06;
GI_Y = M_.params(21);
M_.params(23) = 1.7;
b_Y = M_.params(23);
M_.params(26) = 0.5;
kappa = M_.params(26);
M_.params(25) = 0.87;
rhoa = M_.params(25);
M_.params(22) = 0.04;
INI_Y = M_.params(22);
M_.params(28) = 0.9;
rhoINI = M_.params(28);
M_.params(27) = 0.62;
rhoa_INI = M_.params(27);
M_.params(24) = 0.03;
TR_Y = M_.params(24);
M_.params(30) = 0.9;
rhos = M_.params(30);
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.01/M_.params(20))^2;
M_.Sigma_e(2, 2) = (0.01/M_.params(21))^2;
M_.Sigma_e(3, 3) = 0.0001;
M_.Sigma_e(5, 5) = (0.01/M_.params(22))^2;
M_.Sigma_e(6, 6) = (0.01/M_.params(24))^2;
M_.Sigma_e(7, 7) = 0.01;
options_.irf = 20;
options_.nograph = true;
options_.noprint = true;
options_.order = 1;
options_.periods = 500;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'NK_aging_research_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_aging_research_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_aging_research_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_aging_research_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_aging_research_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_aging_research_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_aging_research_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
