function h=steady_helper3(C_Y,GC_Y,W_Y,TR_Y,rk,phi,s,alpha,mc,zeta,omega,mu)
options=optimset('TolX',1e-30);
h=fsolve( @(h)...
(omega*((C_Y-(1-phi)*s*(1-alpha)*mc/h)/phi-(1-phi)*rk*W_Y/phi-(1-phi)*TR_Y/phi)^((zeta-1)/zeta)+(1-omega)*GC_Y^((zeta-1)/zeta))^(-1)*...
omega*((C_Y-(1-phi)*s*(1-alpha)*mc/h)/phi-(1-phi)*rk*W_Y/phi-(1-phi)*TR_Y/phi)^(-1/zeta)-(h/phi)^mu/mc/(1-alpha)*h,...
[1],options);
end